# Generated by Django 3.1.3 on 2020-11-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agenci',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=200)),
                ('rooms', models.PositiveIntegerField(null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Mieszkanie',
                'verbose_name_plural': 'Mieszkania',
            },
        ),
    ]
