# Generated by Django 3.1.3 on 2020-11-23 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='tytuł')),
                ('description', models.TextField(default='', verbose_name='opis')),
                ('released', models.DateField(blank=True, null=True, verbose_name='data premiery')),
                ('year', models.IntegerField(blank=True, editable=False, null=True)),
                ('imdb', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='imdb')),
                ('poster', models.ImageField(blank=True, null=True, unique=True, upload_to='%Y%m%d', verbose_name='plakat')),
                ('trailer', models.URLField(blank=True, null=True, verbose_name='trailer')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mpaa_rating', models.CharField(choices=[('-', 'Brak'), ('G', 'Dla wszystkich'), ('PG-13', 'Za zgodą rodziców'), ('NC-17', 'Tylko powyżej 17 lat')], default='-', max_length=10, verbose_name='mpaa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
