# Generated by Django 3.1.3 on 2020-11-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'komentarz', 'verbose_name_plural': 'komentarze'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='%Y%m%d', verbose_name='plakat'),
        ),
    ]
