"""
Django settings for alx project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zu5f_02k^4r@yp8z$9wcdusqc76i6$**zw-+hyheabqa3(6peo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["django3.eba-cmv2gftk.eu-west-1.elasticbeanstalk.com",  '127.0.0.1' ]


# Application definition

INSTALLED_APPS = [
    #'multi_captcha_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'movies.apps.MoviesConfig',
    'rentflat', "import_export",
    'crispy_forms',
    'rest_framework', 'drf_yasg', 'rest_framework_api_key',
    #'snowpenguin.django.recaptcha2'
]

RECAPTCHA_PRIVATE_KEY = "6LfhMusZAAAAAIHsUp2HeMvrBUL9h1Js58Y7-NZZ"
RECAPTCHA_PUBLIC_KEY = "6LfhMusZAAAAAFzSzcfTTLtDoH2OV5QQZVoWqu2z"
MULTI_CAPTCHA_ADMIN = {
    "engine" : "recaptcha2"
}

CRISPY_TEMPLATE_PACK = "bootstrap4"

RESTRICT_IPS = False
#ALLOWED_IPS = ['127.0.0.1']

RESTRICT_ADMIN_BY_IPS = True
ALLOWED_ADMIN_IPS = ['127.0.0.1']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ip_restriction.IpWhitelister',
    'movies.custommiddleware.CustomMiddleware'
]

ROOT_URLCONF = 'alx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'movies.context_processors.make_signature'
            ],
        },
    },
]

WSGI_APPLICATION = 'alx.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'pl-pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = "movies/media_folder"
MEDIA_URL = "/media/"

LOGIN_URL = "/login"
LOGIN_REDIRECT_URL = "movie_list"
LOGOUT_REDIRECT_URL = "/logout-done"

# stronicowanie danych z API
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS" : "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE" : 100,
    #"DEFAULT_PERMISSION_CLASSES" : [ "rest_framework_api_key.permissions.HasAPIKey" ]
}